IBM/ibm-common-service-webhook

- Makefile
- SECURITY_CONTACTS
- common/scripts/config_docker.sh
This PR is for integrating ibm common service webhook with the internal artifactory.
/assign @Daniel-Fan 
Fixes #
```release-note
```
> Onborading to artifactory

- Makefile
- common/scripts/multiarch_image.sh
Fix build multi-arch issue
/assign @Daniel-Fan 
Fixes #
```release-note
```
> Fix build multi arch issue

- pkg/webhooks/reconciler.go
Fixes #
Using ignore as the failurepolicy to avoid poding failure after deleting the controller.
/assign @Daniel-Fan 
```release-note
```
> Update failure policy

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- pkg/controller/podpreset/handler.go
> Update log messages

- version/version.go
> bump the image version to 1.1.1

- pkg/controller/podpreset/handler.go
> remove duplicate functions

- Makefile
- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> bump to 1.2.1

- Makefile
- build/Dockerfile
- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> updated ubi image version to 8.3-230 for CS 3.6 EUS release

- pkg/controller/operandrequest/handler.go
Update mapping configmap template
```
common-service-maps.yaml:
- requested-from-namespaces:
- cp4iforFord
map-to-common-service-namespace: common-service-ford
map-default: ibm-common-servies
```
Fixes #
```release-note
```
> update cs mapping configmap

- pkg/controller/operandrequest/handler.go
> update configmap struct

- build/Dockerfile
> updated ubi8 to 8.3-291 to remediate vulnerabilities

- Makefile
- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> bump version to 1.2.3

- build/Dockerfile
> updated ubi8 to 8.3-298

- pkg/webhooks/reconciler.go
- pkg/webhooks/rules.go
> use admissionregistration v1 version api

- pkg/controller/podpreset/podpreset_controller.go
> keeping labels stay in ns 

- .github/dependabot.yml
- build/Dockerfile
> update base image

- Makefile
> docker login when build image

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> bump version to 1.8.0

- common/scripts/next-csv.sh
- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> bump version to 1.10.0

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> bump version to 1.12.0

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> bump version to 1.2.5

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
> bump version to 1.15.0

- pkg/controller/operandrequest/handler.go
Signed-off-by: Daniel Fan <fanyuchensx@gmail.com>
> add csNs into searching loop for OperandRequest NS

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
Signed-off-by: Ben Luzarraga <luzarragaben@ibm.com>
> bump version for 3.19.6

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- deploy/operator.yaml
Signed-off-by: Henry Li <henry.h.li@ibm.com>
Fixes #
```release-note
```
> added runAsNonRoot to security context in container

- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
Signed-off-by: qpdpQ <liyuchen223@gmail.com>
> Bump cd to 3.23

- Makefile
- build/Dockerfile
- common/scripts/config_docker.sh
> new artifactory image endpoint (cs webhook)

- Makefile
- build/Dockerfile
- common/scripts/config_docker.sh
> [ltsr] new artifactory image endpoint (cs webhook)

- Makefile
- build/Dockerfile
- common/scripts/config_docker.sh
> [future] new artifactory image endpoint (cs webhook）

- common/scripts/next-csv.sh
- deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
- version/version.go
Signed-off-by: YuChen <yuchen.shen@mail.utoronto.ca>
> bump to v1.19.1 for v3.23.1
